version: '3.7'

services:
  host:
    image: sqlsharding.host:0.3.0
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@web:4053"
      CLUSTER_PORT: 5110
      STATSD_PORT: 8125
      STATSD_URL: "graphite"
      JAEGER_AGENT_HOST: "jaeger"
    restart: on-failure
    depends_on:
      - "web"
      - "sql"
    scale: 3 
      
  web:
    image: sqlsharding.web:0.3.0
    ports:
      - '8081:80'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      CLUSTER_PORT: 5110
      STATSD_PORT: 8125
      STATSD_URL: "graphite"
      JAEGER_AGENT_HOST: "jaeger"
    restart: on-failure
    
  sql:
    image: akkadotnet.sqlserver:0.1.0
    ports:
      - '1433:1433'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      CLUSTER_PORT: 5110
      STATSD_PORT: 8125
      STATSD_URL: "graphite"
      JAEGER_AGENT_HOST: "jaeger"
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    restart: on-failure